#!/usr/bin/python
import os, sys, getopt

def create_cmakelists(projectname):
    cmakeList = """

    cmake_minimum_required(VERSION 3.15)
    project(""",projectname,""")

    enable_testing()
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

    add_subdirectory(bismuth)
    add_subdirectory(game)
    """

    f = open("CMakeLists.txt", 'w')
    f.write(cmakeList)
    f.close()

def create_project(projectname):
    clone = "git clone git@github.com:vushu/bismuth_cpp.git ."
    deletegit = "rm -rf .git"
    deletecmakelist = "rm CMakeLists.txt"
    os.mkdir(projectname)
    os.chdir(projectname)
    os.system(clone)
    os.system(deletegit)
    os.system(deletecmakelist)
    create_cmakelists(projectname)


def main (argv):

    print("use -h for help")
    print("use -n <projectname> to create new bismuth project")
    projectname = ''
    try:
        opts, args = getopt.getopt(argv, "hn:", ["nproject="])
    except getopt.GetoptError:
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print("To a make a new project do: bismuth-cli.py -n <projectname>")
            sys.exit()
        elif opt in ("-n", "--nproject"):
            projectname = arg
            print("created project: ", projectname)
            create_project(projectname)
            sys.exit()


if __name__ == "__main__":
    main(sys.argv[1:])
